### ISSUE TITLE
CW1

### ISSUE THREAD

**Issue by oleksandrblazhko** [oleksandrblazhko/ai202-prokopenko#10]
https://drive.google.com/file/d/1Jupr5VQFJpOmHJSJY9Vu2JgmrSXgxk2I/view

**Comment by prokop-prokop** [comment]
Завдання 1) 
Їжа/доступність. За мінімальну суму грошей можна купити щось поживне, піти у сад та зірвати наприклад яблуко.
Їжа/зрозумілість. Кожну людину з дитинства водять з собою за покупками у магазин. Тобто кожна людина вміє купувати їжу.
Їжа/цінність. Так як їжу можна купити за мінімальну суму грошей або піти в сад та нарвати фруктів (легкодоступність та дешевизна), мінімальні потреби поживних речовин - коштують небагато.
Їжа/актуальність. Їжа, поживні речовини для усього живого у Світі буде завжди актуальним. Без неї просто не вижити.

**Comment by prokop-prokop** [comment]
Завдання 2)
Feature: Авторизація користувача
Усім авторизованим користувачам надається доступ до основного функціоналу: перегляд фізичних активностей, данні про музичні твори, чат зі співрозмовником з можливим майбутнім коханням, перегляд рекомендованих рецептів приготування їжі.
Feature: Покупка підписки у застосунку
Завдяки підписці у застосунку - відкривається додатковий функціонал, що більше допоможе користувачу. Відеочат зі співрозмовником, більш докладні дані про фізичну активність,  додаткові інструменти для написання музичних творів, більший обсяг бібліотеки рекомендованих рецептів.
Feature: отримання даних про тренди музичних творів
Завдяки цим даним, користувач може дізнатися про популярні тренди, зрозуміти що потрібно зараз аудиторії, що аудиторія полюбляє.

**Comment by oleksandrblazhko** [comment]
Оцінка = 3 бали
